name: build

on:
  push:
  pull_request:

jobs:
  build:
    name: "Build ${{ matrix.go }}"
    strategy:
      matrix:
        go: ["1.22", "1.23"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Vet
      run: go vet ./...
    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2024.1.1"
        install-go: false
        cache-key: ${{ matrix.go }}
    - name: Test
      run: go test -vet=off -race ./...
    - name: Build
      run:  CGO_ENABLED=0 go build
