name: build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  build:
    name: "Build ${{ matrix.go }}"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
    - name: Vet
      run: go vet ./...
    - name: Lint
      uses: golangci/golangci-lint-action@v9
    - name: Test
      run: go test -vet=off -race ./...
    - name: Build
      run:  CGO_ENABLED=0 go build
